<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <LangVersion>latest</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <ImplicitUsings>true</ImplicitUsings>
        <PublishAddinFiles>false</PublishAddinFiles>
        <Configurations>Debug R20;Debug R21;Debug R22;Debug R23;Debug R24;Debug R25</Configurations>
        <Configurations>$(Configurations);Release R20;Release R21;Release R22;Release R23;Release R24;Release R25</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R20'))">
        <RevitVersion>2020</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R21'))">
        <RevitVersion>2021</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R22'))">
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R23'))">
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <StartAction>Program</StartAction>
        <StartProgram>C:\Program Files\Autodesk\Revit $(RevitVersion)\Revit.exe</StartProgram>
        <StartArguments>/language ENG</StartArguments>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Tools\SettingRebars\SettingRebarTags\**" />
      <EmbeddedResource Remove="Tools\SettingRebars\SettingRebarTags\**" />
      <None Remove="Tools\SettingRebars\SettingRebarTags\**" />
      <Page Remove="Tools\SettingRebars\SettingRebarTags\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\FamiliesBases\Metric Detail Item.rft" />
      <None Remove="Resources\FamiliesBases\RebarDetailBase.rfa" />
      <None Remove="Resources\Icons\PluginIcon16.png" />
      <None Remove="Resources\Icons\PluginIcon32.png" />
      <None Remove="Resources\RebarDatas\RebarDataDiameters.json" />
      <None Remove="Resources\RebarDatas\RebarDataWeights.json" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Resources\FamiliesBases\Metric Detail Item.rft">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Resources\FamiliesBases\RebarDetailBase.rfa">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Resources\RebarDatas\RebarDataDiameters.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Resources\RebarDatas\RebarDataWeights.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Chuongmep.Acad.Api.accoremgd" Version="2024.0.1" />
        <PackageReference Include="Chuongmep.Acad.Api.AcCui" Version="2024.0.1" />
        <PackageReference Include="Chuongmep.Acad.Api.acdbmgd" Version="2024.0.1" />
        <PackageReference Include="Chuongmep.Acad.Api.acmgd" Version="2024.0.1" />
        <PackageReference Include="Chuongmep.Acad.Api.AdWindows" Version="2024.0.1" />
        <PackageReference Include="Chuongmep.Acad.Api.Autodesk.AutoCAD.Interop.Common" Version="2024.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Nice3point.Revit.Build.Tasks" Version="1.*" />
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
      <PackageReference Include="Nice3point.Revit.Extensions" Version="2022.3.0" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />
        <PackageReference Include="Revit_All_Main_Versions_IFC_x64" Version="$(RevitVersion).*" />
        <PackageReference Include="Revit_API_x64" Version="2024.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="System.Windows.Forms" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Icons\PluginIcon16.png" />
        <Resource Include="Resources\Icons\PluginIcon32.png" />
        <Resource Include="Resources\Icons\RibbonIcon16.png" />
        <Resource Include="Resources\Icons\RibbonIcon32.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\ShareParameters\" />
      <Folder Include="Tools\CreateScheduleRebar\" />
      <Folder Include="Tools\CreateStructuralRebars\" />
      <Folder Include="Tools\SettingRebars\SettingParameter\" />
      <Folder Include="Tools\ShopDrawingRebars\CreateTagRebars\" />
      <Folder Include="Tools\ShopDrawingRebars\CreatePullOutRebars\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Langs\ApplicationLangs.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ApplicationLangs.resx</DependentUpon>
      </Compile>
      <Compile Update="Properties\ParameterRebarLap.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>ParameterRebarLap.resx</DependentUpon>
      </Compile>
      <Compile Update="Properties\PropertySchemalInfo.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>PropertySchemalInfo.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Langs\ApplicationLangs.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>ApplicationLangs.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Properties\ParameterRebarLap.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>ParameterRebarLap.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Properties\PropertySchemalInfo.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>PropertySchemalInfo.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="if &quot;$(ConfigurationName)&quot; == &quot;Release R21&quot; xcopy &quot;$(TargetDir)*&quot; &quot;$(SolutionDir)\..\InnoSetup\Content\$(RevitVersion)\$(TargetName)&quot; /E /H /C /I /K /D /Y&#xD;&#xA;if &quot;$(ConfigurationName)&quot; == &quot;Release R22&quot; xcopy &quot;$(TargetDir)*&quot; &quot;$(SolutionDir)\..\InnoSetup\Content\$(RevitVersion)\$(TargetName)&quot; /E /H /C /I /K /D /Y&#xD;&#xA;if &quot;$(ConfigurationName)&quot; == &quot;Release R23&quot; xcopy &quot;$(TargetDir)*&quot; &quot;$(SolutionDir)\..\InnoSetup\Content\$(RevitVersion)\$(TargetName)&quot; /E /H /C /I /K /D /Y&#xD;&#xA;if &quot;$(ConfigurationName)&quot; == &quot;Release R24&quot; xcopy &quot;$(TargetDir)*&quot; &quot;$(SolutionDir)\..\InnoSetup\Content\$(RevitVersion)\$(TargetName)&quot; /E /H /C /I /K /D /Y&#xD;&#xA;&#xD;&#xA;copy &quot;$(ProjectDir)*.addin&quot; &quot;$(SolutionDir)\..\InnoSetup\Content\$(RevitVersion)&quot;" />
    </Target>

</Project>